### ISSUE TITLE
this is a error ,please help me ,thank you!

### ISSUE THREAD

**Issue by LooperzZ** [Parskatt/DeDoDe#1]
Traceback (most recent call last):
  File "C:\Users\86132\Desktop\DeDoDe-main\demo\demo_match.py", line 2, in <module>
    from DeDoDe import dedode_detector_L, dedode_descriptor_B
  File "C:\Users\86132\Desktop\DeDoDe-main\DeDoDe\__init__.py", line 1, in <module>
    from .model_zoo import dedode_detector_B, dedode_detector_L, dedode_descriptor_B, dedode_descriptor_G
  File "C:\Users\86132\Desktop\DeDoDe-main\DeDoDe\model_zoo\__init__.py", line 1, in <module>
    from .dedode_models import dedode_detector_B, dedode_detector_L, dedode_descriptor_B, dedode_descriptor_G
  File "C:\Users\86132\Desktop\DeDoDe-main\DeDoDe\model_zoo\dedode_models.py", line 4, in <module>
    from DeDoDe.detectors.dedode_detector import DeDoDeDetector
  File "C:\Users\86132\Desktop\DeDoDe-main\DeDoDe\detectors\dedode_detector.py", line 8, in <module>
    from DeDoDe.utils import sample_keypoints, to_pixel_coords, to_normalized_coords
  File "<fstring>", line 1
    (c=)
      ^
SyntaxError: invalid syntax

**Comment by LooperzZ** [comment]
i change the DeDoDe.utils 472 warnings.warn(f"Number of channels {c=} > 3, assuming first 3 are rgb")  >>  warnings.warn(f"Number of channels {c} > 3, assuming first 3 are rgb").after that,this is a new error:

Traceback (most recent call last):
  File "C:\Users\86132\Desktop\DeDoDe-main\demo\demo_match.py", line 2, in <module>
    from DeDoDe import dedode_detector_L, dedode_descriptor_B
  File "C:\Users\86132\Desktop\DeDoDe-main\DeDoDe\__init__.py", line 1, in <module>
    from .model_zoo import dedode_detector_B, dedode_detector_L, dedode_descriptor_B, dedode_descriptor_G
  File "C:\Users\86132\Desktop\DeDoDe-main\DeDoDe\model_zoo\__init__.py", line 1, in <module>
    from .dedode_models import dedode_detector_B, dedode_detector_L, dedode_descriptor_B, dedode_descriptor_G
  File "C:\Users\86132\Desktop\DeDoDe-main\DeDoDe\model_zoo\dedode_models.py", line 4, in <module>
    from DeDoDe.detectors.dedode_detector import DeDoDeDetector
  File "C:\Users\86132\Desktop\DeDoDe-main\DeDoDe\detectors\dedode_detector.py", line 8, in <module>
    from DeDoDe.utils import sample_keypoints, to_pixel_coords, to_normalized_coords
  File "C:\Users\86132\Desktop\DeDoDe-main\DeDoDe\utils.py", line 88, in <module>
    def fast_inv_2x2(matrix: tuple[...,2,2], eps = 1e-10):
TypeError: 'type' object is not subscriptable

**Comment by Parskatt** [comment]
You can remove the type annotations if you want. Probably you're using an older python which doesnt support them.

**Comment by LooperzZ** [comment]
okk,thank you !
